---
deployment:
  tasks:
    - export DEPLOYPATH=/home/arooteaj/goa.callgirlsinlucknow.in/
    - /bin/cp * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -name .git -exec rm -rf {} \;  # Remove .git directories
    - /bin/find $DEPLOYPATH -type f -name .gitignore -exec rm -f {} \;  # Remove .gitignore files
